# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.locale.1.9.0.schema.json

PackageIdentifier: Zhouqluo.Bilidown
PackageVersion: 1.2.5
PackageLocale: zh-CN
Publisher: 王子周棋洛
PublisherUrl: https://zhouql.vip/
Author: 周棋洛
PackageName: bilidown
PackageUrl: https://zhouql.vip/bilibili/pc/
License: 免费软件
Copyright: Copyright © 2024 王子周棋洛
ShortDescription: 一款简洁好用、纯净免费的 B 站视频下载软件。
Tags:
- bilibili
- b站
- 哔哩哔哩
ReleaseNotes: |-
  🛠️新增高度开放的大于一项创建文件夹开关。
  🛠️新增文件夹名前添加序号开关。
  🛠️删除批量类型大于自动创建文件夹的行为。
  🛠️优化对已删除等无效视频的解析体验。
  🛠️优化部分辅助工具的使用体验。
  🛠️修复对已删除视频判断不准确问题。
  🛠️修复 srt 字幕转 txt 文本转换问题。
  🛠️修复了一些已知问题。
ReleaseNotesUrl: https://zhouql.vip/bilibili/pcversion/
Documentations:
- DocumentLabel: 文档
  DocumentUrl: https://zhouql.vip/bilibili/doc/
ManifestType: locale
ManifestVersion: 1.9.0
